### ISSUE TITLE
Menuitem

### ISSUE THREAD

**Issue by heikostueber** [humhub/humhub-modules-translation#11]
The module is working fine for me in the beta, but one thing is important:

Now the user see a menuitem but can't enter it. It should be only displayed for admin in the menu.

**Comment by arnfinnkristensen** [comment]
The menu itme should only be visible for the administrator users. Today it is visible for everybody, but if a "normal" user click's on it he/she get an error message.

**Comment by luke-** [comment]
It's build for our internal translation site which can be used by "non-administrative" users.
