### ISSUE TITLE
All strings returned as "Invalid content id given!"

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub-modules-translation#18]
![image](https://user-images.githubusercontent.com/12234510/27229617-87d9fde0-52ac-11e7-9f8c-72d5f7fe4fc0.png)

**Comment by mtcoliveira** [comment]
@acs-ferreira I`ve the same problem. Did you solve your?

**Comment by acs-ferreira** [comment]
I've removed and reinstalled.
