### ISSUE TITLE
After saving, '=>' is converted to '=&gt;'

### ISSUE THREAD

**Issue by sakurafarm** [humhub/humhub-modules-translation#27]
I tried to translate the following phrase contained in the _UserModule.profile_.
`One option per line. Key=>Value Format (e.g. yes=>Yes)`

When saved, `=>` is converted to `=&gt;`.

Is there a way to avoid being escaped?

**Comment by buddh4** [comment]
The encoding per se is not the problem, the problem is that the HForm used for rendering the profile form double encodes this hint. I've opened an issue: https://github.com/humhub/humhub/issues/4140
