### ISSUE TITLE
HTML Special Entities Leaking

### ISSUE THREAD

**Issue by ArchBlood** [humhub/humhub-modules-translation#28]
![Screenshot_3](https://user-images.githubusercontent.com/35392110/84099937-c74d8d80-a9d8-11ea-882e-89a62776e539.png)

**Comment by buddh4** [comment]
Its defined like this in code:

```
 'loginFilter' => Yii::t('LdapModule.base', 'Defines the filter to apply, when login is attempted. %s replaces the username in the login action. Example: &quot;(sAMAccountName=%s)&quot; or &quot;(uid=%s)&quot;'),
           
```

**Comment by ArchBlood** [comment]
I completely forgot what I reported here :thinking:

**Comment by buddh4** [comment]
I think you thought the translation module produced those encoded test, but the original translation contains those entities, so its not an issue with the translation module. This is not a bug, but unfortunately it gets a bit harder to translate like this, but we'd need to change the original message.
