### ISSUE TITLE
It does not save translations.

### ISSUE THREAD

**Issue by orfinoz** [humhub/humhub-modules-translation#34]
It always writes "There is no language related space available for language ** "

I don't know why this happened, but I tried everything, including installing older versions, and couldn't run it.

**Comment by luke-** [comment]
On our translation community or did you install the module yourself?

**Comment by orfinoz** [comment]
> On our translation community or did you install the module yourself?

I installed it myself. It's working on the community so I thought it was my problem. I tried this over and over thinking it was a bug on my own setup. I tried again on different versions of humhub as well as on different php versions but I keep getting the same error.

**Comment by luke-** [comment]
You have to create a space for each language, are you aware of that?

**Comment by orfinoz** [comment]
> You have to create a space for each language, are you aware of that?

How exactly and in what folder should I do this? I am not doing anything except the installation steps in the description;

Installation:
Install

Download & Put files into /protected/modules/translation/
Or: git submodule add https://github.com/humhub/humhub-modules-translation.git protected/modules/translation
Enable it under Admin -> Modules

Open via Administration -> Manage -> Translation

**Comment by orfinoz** [comment]
> You have to create a space for each language, are you aware of that?

Whatever I am missing or doing wrong, can you help me please?

**Comment by buddh4** [comment]
perhaps we should just skip this validation for system admins (or by permission)
