### ISSUE TITLE
Activity / Mail Summary shows empty translation text

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub-modules-translation#36]
I assume it shows the old translation instead of the new:

![grafik](https://user-images.githubusercontent.com/9800854/96157744-fb026c00-0f12-11eb-87f8-29411b09ca3f.png)

**Comment by luke-** [comment]
It's also affects the Activities Panel
![image](https://user-images.githubusercontent.com/4736168/107259009-c45ddd80-6a3c-11eb-8509-60d5933ddde8.png)

**Comment by yurabakhtin** [comment]
@luke- @buddh4 PR https://github.com/humhub/humhub-modules-translation/pull/39:

<img width="614" alt="mail_summary" src="https://user-images.githubusercontent.com/6995524/107329225-e9942f80-6ac0-11eb-9658-715cbfb0a135.png">

<img width="286" alt="activities" src="https://user-images.githubusercontent.com/6995524/107329231-eb5df300-6ac0-11eb-8e55-366887acf547.png">
