### ISSUE TITLE
There is no language related space available for language xx

### ISSUE THREAD

**Issue by blackPantherOS** [humhub/humhub-modules-translation#38]
Hi, 
I can't save translations because i get this error messages for all modules:

```
"The translations for "comment / XX / base" could not be loaded:
There is no language related space available for language XX"
```
XX=anylanguage
I welocme any idea!

**Comment by luke-** [comment]
The module is not intended for external use, it is only for our translate.humhub.org site.

The module needs a separate space for each language code (e.g. DE).
