### ISSUE TITLE
Fatal error: Class 'ZipArchive' not found in /home/frenzee/public_html/protected/modules_core/admin/libs/OnlineModuleManager.php on line 87

### ISSUE THREAD

**Issue by maddox22** [humhub/humhub-modules-translation#7]
i m going to install modules but i have got this problem anyone help me 

Fatal error: Class 'ZipArchive' not found in /home/frenzee/public_html/protected/modules_core/admin/libs/OnlineModuleManager.php on line 87

**Comment by luke-** [comment]
Please see: https://github.com/humhub/humhub/issues/550
